### ISSUE TITLE
Duplicate Results

### ISSUE THREAD

**Issue by dmofot** [opendata/lmgtdfy#31] opened 2015-02-21 18:42 UTC
It appears the search is returning duplicate results, usually in 12's (11 duplicates and 1 original), at least for [cityofboston.gov](http://lmgtdfy.usopendata.org/cityofboston.gov/).

**Comment by waldoj** [comment] 2015-02-21 18:48
Closed as, ironically, a duplicate of #18. :)

**Closed by waldoj** 2015-02-21 18:48 UTC
